version: '3'

services:
  site:
    command: jekyll serve
    image: jekyll/jekyll:latest
    ports:
      - "4000:4000"
      - "35729:35729"
      - "3000:3000"
      -   "80:4000"
    volumes:
      - $PWD:/srv/jekyll
      - $PWD/vendor/bundle:/usr/local/bundle
