version: '3'

services:
  site:
    build:
      context: .
    command: jekyll serve
    container_name: boream-blog
    image: boream/boream-blog
    ports:
      - "4000:4000"
    volumes:
      - .:/srv/jekyll
      - .:/usr/local/bundle
